//! # NULL Digest Provider Implementation
//!
//! A no-op passthrough digest that accepts all input and produces zero-length
//! output. Used as a sentinel/placeholder when a valid digest context is needed
//! but no actual hashing should occur (e.g., RSA-PSS with `id-mgf1-NULL`, or
//! test infrastructure that requires a digest algorithm slot).
//!
//! ## Properties
//!
//! - **Block size:** 0 bytes
//! - **Digest size:** 0 bytes
//! - **Flags:** 0 (none)
//!
//! ## C Source Reference
//!
//! Replaces `providers/implementations/digests/null_prov.c` (53 lines).
//!
//! The C implementation defines `NULLMD_CTX` with a trivial `unsigned char nothing`
//! field and three operations that always succeed: `null_init`, `null_update`, and
//! `null_final` (which sets `*outl = 0`). Generated via
//! `IMPLEMENT_digest_functions(nullmd, NULLMD_CTX, 0, 0, 0, ...)`.
//!
//! ## Zero Unsafe
//!
//! All code in this module is 100% safe Rust (Rule R8).

use crate::traits::{AlgorithmDescriptor, DigestContext, DigestProvider};
use super::common::{DigestFlags, default_get_params};
use openssl_common::error::ProviderResult;
use openssl_common::param::ParamSet;

// =============================================================================
// NullDigestProvider — Public Provider Struct
// =============================================================================

/// NULL message digest provider.
///
/// Accepts all input data but produces zero-length output.
/// Block size: 0, Digest size: 0, Flags: 0.
///
/// # Algorithm Names
///
/// Registered under: `["NULL"]` with property `"provider=default"`.
///
/// # C Mapping
///
/// Replaces the `ossl_nullmd_functions` dispatch table from `null_prov.c`,
/// generated by the `IMPLEMENT_digest_functions(nullmd, NULLMD_CTX, 0, 0, 0, ...)`
/// macro invocation.
#[derive(Debug, Clone)]
pub struct NullDigestProvider;

impl DigestProvider for NullDigestProvider {
    /// Returns the canonical algorithm name `"NULL"`.
    fn name(&self) -> &'static str {
        "NULL"
    }

    /// Returns `0` — the NULL digest has no block structure.
    fn block_size(&self) -> usize {
        0
    }

    /// Returns `0` — the NULL digest produces no output bytes.
    fn digest_size(&self) -> usize {
        0
    }

    /// Creates a new `NullDigestContext` — a zero-cost no-op context.
    ///
    /// Always succeeds; the NULL digest has no initialization requirements.
    fn new_ctx(&self) -> ProviderResult<Box<dyn DigestContext>> {
        Ok(Box::new(NullDigestContext))
    }
}

// =============================================================================
// NullDigestContext — Internal Context (Not Public)
// =============================================================================

/// NULL digest context — all operations are no-ops.
///
/// Translates the C `NULLMD_CTX` struct which contains a single
/// `unsigned char nothing` field. In Rust this is a zero-sized type
/// since no state is needed.
///
/// - `init()` always succeeds.
/// - `update()` accepts and silently discards all input data.
/// - `finalize()` returns an empty `Vec<u8>` (matching C `*outl = 0`).
/// - `get_params()` delegates to `default_get_params` with `block_size=0`,
///   `digest_size=0`, and [`DigestFlags::empty()`].
/// - `set_params()` is a no-op that accepts any parameter set.
#[derive(Debug, Clone)]
struct NullDigestContext;

impl DigestContext for NullDigestContext {
    /// Initializes the NULL digest context (no-op).
    ///
    /// Translates C `null_init()` which unconditionally returns 1.
    /// Any parameters provided are accepted and ignored since the NULL
    /// digest has no configurable behaviour.
    fn init(&mut self, _params: Option<&ParamSet>) -> ProviderResult<()> {
        Ok(())
    }

    /// Absorbs input data (no-op — data is silently discarded).
    ///
    /// Translates C `null_update()` which unconditionally returns 1
    /// without reading the input buffer.
    fn update(&mut self, _data: &[u8]) -> ProviderResult<()> {
        Ok(())
    }

    /// Finalizes the NULL digest, returning an empty vector (0 bytes).
    ///
    /// Translates the custom `PROV_FUNC_DIGEST_FINAL` override in
    /// `null_prov.c` which sets `*outl = 0` and returns 1. The C
    /// implementation also checks `ossl_prov_is_running()` before
    /// returning; in Rust we always succeed since provider lifecycle
    /// is managed by the provider framework.
    ///
    /// **Rule R5:** Returns `Ok(Vec::new())` instead of a sentinel null
    /// pointer or negative length.
    fn finalize(&mut self) -> ProviderResult<Vec<u8>> {
        Ok(Vec::new())
    }

    /// Creates a deep copy of this context.
    ///
    /// Since `NullDigestContext` is a zero-sized type, duplication is trivial.
    fn duplicate(&self) -> ProviderResult<Box<dyn DigestContext>> {
        Ok(Box::new(NullDigestContext))
    }

    /// Returns the digest parameter set with `block_size=0` and `digest_size=0`.
    ///
    /// Delegates to `default_get_params` with `(0, 0, DigestFlags::empty())`
    /// which mirrors the C `IMPLEMENT_digest_functions` macro behaviour calling
    /// `ossl_digest_default_get_params(0, 0, 0)` for the NULL digest.
    fn get_params(&self) -> ProviderResult<ParamSet> {
        default_get_params(0, 0, DigestFlags::empty())
    }

    /// Sets context parameters (no-op for the NULL digest).
    ///
    /// The NULL digest has no settable context parameters. Any parameters
    /// provided are silently accepted without error, matching the C
    /// behaviour where `nullmd_settable_ctx_params` is NULL.
    fn set_params(&mut self, _params: &ParamSet) -> ProviderResult<()> {
        Ok(())
    }
}

// =============================================================================
// Algorithm Descriptors
// =============================================================================

/// Returns algorithm descriptors for the NULL digest.
///
/// Registers the NULL digest under the name `"NULL"` with property
/// `"provider=default"`. Called by `digests::mod::descriptors()` during
/// provider initialization to populate the default provider's algorithm
/// table.
///
/// # C Mapping
///
/// Replaces the static dispatch table entry
/// `{ "NULL", "provider=default", ossl_nullmd_functions }` from `defltprov.c`.
pub fn descriptors() -> Vec<AlgorithmDescriptor> {
    vec![AlgorithmDescriptor {
        names: vec!["NULL"],
        property: "provider=default",
        description: "NULL digest (0-bit output, passthrough sentinel)",
    }]
}

// =============================================================================
// Unit Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify provider metadata matches C constants: block=0, digest=0.
    #[test]
    fn test_null_provider_properties() {
        let provider = NullDigestProvider;
        assert_eq!(provider.name(), "NULL");
        assert_eq!(provider.block_size(), 0);
        assert_eq!(provider.digest_size(), 0);
    }

    /// Verify the full digest lifecycle: init → update → finalize produces empty output.
    #[test]
    fn test_null_context_lifecycle() {
        let provider = NullDigestProvider;
        let mut ctx = provider.new_ctx().expect("new_ctx should succeed");

        ctx.init(None).expect("init should succeed");
        ctx.update(b"this data is silently discarded")
            .expect("update should succeed");
        ctx.update(b"more discarded data")
            .expect("second update should succeed");

        let digest = ctx.finalize().expect("finalize should succeed");
        assert!(digest.is_empty(), "NULL digest must produce 0-byte output");
    }

    /// Verify finalize returns empty even without any update calls.
    #[test]
    fn test_null_context_finalize_without_update() {
        let provider = NullDigestProvider;
        let mut ctx = provider.new_ctx().expect("new_ctx should succeed");
        ctx.init(None).expect("init should succeed");

        let digest = ctx.finalize().expect("finalize should succeed");
        assert!(digest.is_empty(), "NULL digest must produce 0-byte output");
    }

    /// Verify context duplication produces an independent copy.
    #[test]
    fn test_null_context_duplicate() {
        let provider = NullDigestProvider;
        let ctx = provider.new_ctx().expect("new_ctx should succeed");

        let mut dup = ctx.duplicate().expect("duplicate should succeed");
        dup.init(None).expect("init on duplicate should succeed");
        let digest = dup.finalize().expect("finalize on duplicate should succeed");
        assert!(digest.is_empty());
    }

    /// Verify get_params returns block_size=0 and digest_size=0.
    #[test]
    fn test_null_context_get_params() {
        let provider = NullDigestProvider;
        let ctx = provider.new_ctx().expect("new_ctx should succeed");

        let params = ctx.get_params().expect("get_params should succeed");
        // The params should contain blocksize and size keys
        // populated by default_get_params(0, 0, DigestFlags::empty())
        assert!(
            params.len() > 0,
            "get_params should return a non-empty parameter set"
        );
    }

    /// Verify set_params is a no-op that always succeeds.
    #[test]
    fn test_null_context_set_params_noop() {
        let provider = NullDigestProvider;
        let mut ctx = provider.new_ctx().expect("new_ctx should succeed");

        let params = ParamSet::new();
        ctx.set_params(&params)
            .expect("set_params should succeed for empty params");
    }

    /// Verify algorithm descriptors are correct.
    #[test]
    fn test_null_descriptors() {
        let descs = descriptors();
        assert_eq!(descs.len(), 1, "NULL digest should have exactly one descriptor");
        assert_eq!(descs[0].names, vec!["NULL"]);
        assert_eq!(descs[0].property, "provider=default");
        assert!(!descs[0].description.is_empty());
    }
}
