//! Shared cipher infrastructure: modes, flags, IV generation, padding,
//! AEAD state machines, parameter keys, and helper functions.
//!
//! This module provides common types and utilities used by all cipher
//! implementations. Translates the C `ciphercommon.c`, `ciphercommon_hw.c`,
//! `ciphercommon_block.c`, `ciphercommon_gcm.c`, `ciphercommon_ccm.c`,
//! and related files.

// =============================================================================
// Cipher Operating Modes
// =============================================================================

/// Symmetric cipher operating modes.
///
/// Each variant corresponds to a standard block cipher mode of operation
/// or a stream cipher mode. The mode determines how plaintext blocks are
/// processed and how the cipher state evolves across blocks.
///
/// Replaces the C `EVP_CIPH_*_MODE` constants from `include/openssl/evp.h`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum CipherMode {
    /// Electronic Codebook — each block encrypted independently.
    Ecb = 1,
    /// Cipher Block Chaining — each block is XOR-combined with previous ciphertext.
    Cbc = 2,
    /// Output Feedback — turns block cipher into stream cipher.
    Ofb = 3,
    /// Cipher Feedback — turns block cipher into self-synchronizing stream cipher.
    Cfb = 4,
    /// Counter mode — turns block cipher into stream cipher using incrementing counter.
    Ctr = 5,
    /// Galois/Counter Mode — authenticated encryption with associated data.
    Gcm = 6,
    /// Counter with CBC-MAC — authenticated encryption with associated data.
    Ccm = 7,
    /// Offset Codebook Mode — parallelizable AEAD mode.
    Ocb = 8,
    /// XEX-based Tweaked-codebook mode with ciphertext Stealing — disk encryption.
    Xts = 9,
    /// Synthetic Initialization Vector — nonce-misuse resistant AEAD.
    Siv = 10,
    /// GCM-SIV — nonce-misuse resistant variant of GCM.
    GcmSiv = 11,
    /// Key Wrap mode (RFC 3394 / RFC 5649).
    Wrap = 12,
    /// CBC with Ciphertext Stealing — allows non-block-aligned plaintext.
    CbcCts = 13,
    /// Stream cipher mode (e.g., `ChaCha20`, RC4).
    Stream = 14,
}

impl std::fmt::Display for CipherMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Self::Ecb => "ECB",
            Self::Cbc => "CBC",
            Self::Ofb => "OFB",
            Self::Cfb => "CFB",
            Self::Ctr => "CTR",
            Self::Gcm => "GCM",
            Self::Ccm => "CCM",
            Self::Ocb => "OCB",
            Self::Xts => "XTS",
            Self::Siv => "SIV",
            Self::GcmSiv => "GCM-SIV",
            Self::Wrap => "WRAP",
            Self::CbcCts => "CBC-CTS",
            Self::Stream => "STREAM",
        };
        write!(f, "{name}")
    }
}

// =============================================================================
// Cipher Capability Flags
// =============================================================================

bitflags::bitflags! {
    /// Bitfield flags describing cipher capabilities and requirements.
    ///
    /// Replaces the C `EVP_CIPH_FLAG_*` constants from `include/openssl/evp.h`.
    /// Multiple flags can be combined to describe the full set of capabilities
    /// for a cipher implementation.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct CipherFlags: u32 {
        /// Cipher provides authenticated encryption with associated data (AEAD).
        /// Set for GCM, CCM, OCB, SIV, GCM-SIV, ChaCha20-Poly1305.
        const AEAD = 0x0001;

        /// Cipher requires a custom IV (not randomly generated by the framework).
        /// The caller must supply the IV via set_params before encryption.
        const CUSTOM_IV = 0x0002;

        /// Cipher uses Ciphertext Stealing (CTS) to handle non-block-aligned
        /// plaintext without padding. Set for CBC-CTS mode variants.
        const CTS = 0x0004;

        /// Cipher supports TLS 1.0 multi-block optimization for pipelining
        /// multiple TLS records in a single cipher operation.
        const TLS1_MULTIBLOCK = 0x0008;

        /// Cipher requires a randomly generated key (used by RC4 and similar
        /// stream ciphers that need per-session key diversification).
        const RAND_KEY = 0x0010;

        /// Cipher supports variable-length keys (e.g., Blowfish: 32-448 bits,
        /// RC2: 8-1024 bits, RC4: 40-2048 bits).
        const VARIABLE_LENGTH = 0x0020;

        /// The decryption operation uses a different algorithm or key schedule
        /// than encryption (e.g., AES with separate encrypt/decrypt key expansions).
        const INVERSE_CIPHER = 0x0040;

        /// Cipher supports encrypt-then-MAC composition for TLS record protection.
        /// Used by AES-CBC-HMAC-SHA composite ciphers.
        const ENC_THEN_MAC = 0x0080;
    }
}

// =============================================================================
// IV Generation Strategy
// =============================================================================

/// Strategy for generating Initialization Vectors (IVs) or nonces.
///
/// Determines how the IV/nonce is produced before each encryption operation.
/// Replaces the C `EVP_CIPH_GCM_SET_IV_*` flags from `include/openssl/evp.h`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum IvGeneration {
    /// No IV generation — the caller must supply the IV explicitly.
    /// Used for modes that don't need an IV (ECB) or where the caller
    /// manages IV generation externally.
    #[default]
    None,

    /// IV is generated randomly using the DRBG.
    /// Suitable for most AEAD modes where nonce uniqueness is critical.
    Random,

    /// IV is generated by incrementing a counter from an initial value.
    /// Used for TLS 1.3 nonce construction where the IV is XOR-combined with
    /// a per-record sequence number.
    Sequential,
}

impl std::fmt::Display for IvGeneration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Self::None => "none",
            Self::Random => "random",
            Self::Sequential => "sequential",
        };
        write!(f, "{name}")
    }
}

// =============================================================================
// Cipher Parameter Keys
// =============================================================================

/// String constants for cipher parameter keys used in `get_params()` and
/// `set_params()` operations.
///
/// These constants replace the C `OSSL_CIPHER_PARAM_*` macros from
/// `include/openssl/core_names.h`. They identify parameter fields in the
/// typed parameter system (`openssl_common::param::ParamSet`).
pub mod param_keys {
    /// Whether PKCS#7 padding is enabled (`u32`: 0 = no, 1 = yes).
    pub const PADDING: &str = "padding";

    /// The cipher mode of operation as a string (e.g., "GCM", "CBC").
    pub const MODE: &str = "mode";

    /// The key length in bytes (`usize`).
    pub const KEYLEN: &str = "keylen";

    /// The IV/nonce length in bytes (`usize`).
    pub const IVLEN: &str = "ivlen";

    /// The cipher block size in bytes (`usize`). Stream ciphers report 1.
    pub const BLOCK_SIZE: &str = "blocksize";

    /// Whether the cipher provides AEAD (`u32`: 0 = no, 1 = yes).
    pub const AEAD: &str = "aead";

    /// The AEAD authentication tag value (`Vec<u8>`). Set after encryption,
    /// provided before decryption.
    pub const AEAD_TAG: &str = "tag";

    /// The AEAD authentication tag length in bytes (`usize`).
    pub const AEAD_TAGLEN: &str = "taglen";

    /// TLS additional authenticated data for AEAD ciphers (`Vec<u8>`).
    /// Contains the TLS record header used as AAD in TLS 1.2 AEAD construction.
    pub const AEAD_TLS1_AAD: &str = "tlsaad";

    /// The padding length added by TLS AAD processing (`usize`).
    pub const AEAD_TLS1_AAD_PAD: &str = "tlsaadpad";

    /// The fixed portion of the TLS IV for AEAD ciphers (`Vec<u8>`).
    /// Combined with the per-record explicit nonce to form the full IV.
    pub const AEAD_TLS1_IV_FIXED: &str = "tlsivfixed";

    /// Whether the IV is generated randomly by the cipher (`u32`).
    pub const AEAD_IV_RANDOM: &str = "ivrandom";

    /// The CTS (Ciphertext Stealing) variant string for CBC-CTS mode.
    pub const CTS_MODE: &str = "cts_mode";

    /// The TLS MAC value for composite cipher modes (`Vec<u8>`).
    pub const TLS_MAC: &str = "tls-mac";

    /// The TLS MAC size in bytes (`usize`).
    pub const TLS_MAC_SIZE: &str = "tls-mac-size";

    /// The TLS protocol version (`u32`).
    pub const TLS_VERSION: &str = "tls-version";

    /// Whether the cipher state was updated during the last operation (`u32`).
    pub const UPDATED: &str = "updated";

    /// A numeric identifier for the cipher algorithm (`u32`).
    pub const NUM: &str = "num";

    /// Whether the cipher uses randomly generated keys (`u32`).
    pub const HAS_RAND_KEY: &str = "has-randkey";

    /// Speed/throughput hint for cipher selection (`u32`).
    pub const SPEED: &str = "speed";

    /// Whether the cipher uses a custom (caller-supplied) IV (`u32`).
    pub const CUSTOM_IV: &str = "custom-iv";
}

// =============================================================================
// AEAD State Machines
// =============================================================================

/// State machine for GCM (Galois/Counter Mode) cipher operations.
///
/// Tracks the progression of a GCM encryption or decryption operation
/// through its required phases: initialization → AAD processing → data
/// processing → finalization.
///
/// Replaces the implicit state tracking in C's `PROV_GCM_CTX` from
/// `providers/implementations/ciphers/ciphercommon_gcm.c`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GcmState {
    /// Context created but not yet initialized with key and IV.
    Uninitialized,
    /// Key and IV have been set; ready to process AAD or plaintext.
    Initialized,
    /// Processing additional authenticated data (AAD).
    ProcessingAad,
    /// Processing plaintext/ciphertext data.
    ProcessingData,
    /// Operation finalized; tag has been generated (encrypt) or verified (decrypt).
    Finalized,
    /// An error occurred; context is no longer usable.
    Error,
}

/// State machine for CCM (Counter with CBC-MAC) cipher operations.
///
/// CCM requires the total plaintext length to be known before processing
/// begins, which introduces an additional `LengthSet` state compared to GCM.
///
/// Replaces the implicit state tracking in C's `PROV_CCM_CTX` from
/// `providers/implementations/ciphers/ciphercommon_ccm.c`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CcmState {
    /// Context created but not yet initialized.
    Uninitialized,
    /// Key and IV have been set; waiting for length information.
    Initialized,
    /// Total data length has been specified; ready for AAD or data.
    LengthSet,
    /// Processing additional authenticated data (AAD).
    ProcessingAad,
    /// Processing plaintext/ciphertext data.
    ProcessingData,
    /// Operation finalized; tag generated or verified.
    Finalized,
    /// An error occurred; context is no longer usable.
    Error,
}

// =============================================================================
// Padding Helpers
// =============================================================================

/// Applies PKCS#7 padding to the given data buffer.
///
/// PKCS#7 padding appends N bytes each with value N, where N is the number
/// of bytes needed to reach the next block boundary. If the data is already
/// block-aligned, a full block of padding is added.
///
/// # Parameters
///
/// - `data`: The plaintext data to pad.
/// - `block_size`: The cipher block size in bytes (must be 1..=255).
///
/// # Returns
///
/// A new `Vec<u8>` containing the original data with PKCS#7 padding appended.
///
/// # Panics
///
/// Panics if `block_size` is 0 or greater than 255.
pub fn pkcs7_pad(data: &[u8], block_size: usize) -> Vec<u8> {
    assert!(block_size > 0 && block_size <= 255, "block_size must be 1..=255");
    let pad_len = block_size - (data.len() % block_size);
    let mut padded = Vec::with_capacity(data.len() + pad_len);
    padded.extend_from_slice(data);
    // TRUNCATION: pad_len ∈ 1..=block_size and block_size ≤ 255 (asserted above),
    // so pad_len always fits in u8. The assert on line 312 guarantees this is lossless.
    #[allow(clippy::cast_possible_truncation)]
    let pad_byte = pad_len as u8;
    padded.resize(padded.len() + pad_len, pad_byte);
    padded
}

/// Removes and validates PKCS#7 padding from the given data buffer.
///
/// Verifies that the padding bytes are consistent (all equal to the padding
/// length value) and strips them from the data.
///
/// # Parameters
///
/// - `data`: The padded data buffer.
/// - `block_size`: The cipher block size in bytes (must be 1..=255).
///
/// # Returns
///
/// - `Ok(Vec<u8>)` containing the data with padding removed.
/// - `Err(PaddingError)` if the padding is invalid (empty data, zero pad byte,
///   pad length exceeds data length, or inconsistent pad bytes).
pub fn pkcs7_unpad(data: &[u8], block_size: usize) -> Result<Vec<u8>, PaddingError> {
    if data.is_empty() || data.len() % block_size != 0 {
        return Err(PaddingError::InvalidLength);
    }
    let pad_byte = *data.last().ok_or(PaddingError::InvalidLength)?;
    let pad_len = usize::from(pad_byte);
    if pad_len == 0 || pad_len > block_size || pad_len > data.len() {
        return Err(PaddingError::InvalidPadByte);
    }
    // Verify all padding bytes are correct (constant-time would be better
    // for production; this is the structural translation)
    let start = data.len() - pad_len;
    for &byte in &data[start..] {
        if byte != pad_byte {
            return Err(PaddingError::InconsistentPadding);
        }
    }
    Ok(data[..start].to_vec())
}

/// Error type for PKCS#7 padding validation failures.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PaddingError {
    /// Data length is zero or not a multiple of the block size.
    InvalidLength,
    /// Padding byte value is zero or exceeds the block size.
    InvalidPadByte,
    /// Not all trailing bytes match the expected padding value.
    InconsistentPadding,
}

impl std::fmt::Display for PaddingError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidLength => write!(f, "data length is invalid for unpadding"),
            Self::InvalidPadByte => write!(f, "padding byte value is invalid"),
            Self::InconsistentPadding => write!(f, "padding bytes are inconsistent"),
        }
    }
}

impl std::error::Error for PaddingError {}

// =============================================================================
// Generic Cipher Helpers
// =============================================================================

/// Constructs the common set of algorithm parameters for a cipher.
///
/// Returns a list of `(key, value)` pairs describing the cipher's
/// fundamental properties: mode, key length, IV length, block size,
/// AEAD capability, and padding status.
///
/// Translates the C `ossl_cipher_generic_get_params()` function from
/// `providers/implementations/ciphers/ciphercommon.c`.
///
/// # Parameters
///
/// - `mode`: The cipher operating mode.
/// - `key_len`: Key length in bytes.
/// - `iv_len`: IV/nonce length in bytes.
/// - `block_size`: Block size in bytes (1 for stream ciphers).
/// - `flags`: Cipher capability flags.
pub fn generic_get_params(
    mode: CipherMode,
    key_len: usize,
    iv_len: usize,
    block_size: usize,
    flags: CipherFlags,
) -> Vec<(&'static str, String)> {
    let mut params = Vec::new();
    params.push((param_keys::MODE, mode.to_string()));
    params.push((param_keys::KEYLEN, key_len.to_string()));
    params.push((param_keys::IVLEN, iv_len.to_string()));
    params.push((param_keys::BLOCK_SIZE, block_size.to_string()));
    params.push((
        param_keys::AEAD,
        if flags.contains(CipherFlags::AEAD) { "1" } else { "0" }.to_string(),
    ));
    params.push((
        param_keys::PADDING,
        if mode == CipherMode::Ecb || mode == CipherMode::Cbc { "1" } else { "0" }.to_string(),
    ));
    params.push((
        param_keys::CUSTOM_IV,
        if flags.contains(CipherFlags::CUSTOM_IV) { "1" } else { "0" }.to_string(),
    ));
    params
}

/// Validates and initializes a cipher key.
///
/// Checks that the provided key length matches the expected key length
/// for the cipher. Returns the validated key material as a byte vector.
///
/// Translates part of `ossl_cipher_generic_initkey()` from
/// `providers/implementations/ciphers/ciphercommon.c`.
///
/// # Parameters
///
/// - `key`: The raw key material.
/// - `expected_len`: The expected key length in bytes.
///
/// # Returns
///
/// - `Ok(Vec<u8>)` with the validated key bytes.
/// - `Err(String)` if the key length doesn't match.
pub fn generic_init_key(key: &[u8], expected_len: usize) -> Result<Vec<u8>, String> {
    if key.len() != expected_len {
        return Err(format!(
            "invalid key length: expected {expected_len} bytes, got {} bytes",
            key.len()
        ));
    }
    Ok(key.to_vec())
}

/// Processes a block-mode cipher update for data that must be block-aligned.
///
/// Buffers partial blocks and processes complete blocks. Remaining partial
/// block data is returned for the caller to buffer.
///
/// Translates the block-update logic from `ossl_cipher_generic_block_update()`
/// in `providers/implementations/ciphers/ciphercommon.c`.
///
/// # Parameters
///
/// - `input`: Input data to process.
/// - `block_size`: The cipher block size in bytes.
/// - `pending`: Previously buffered partial block data.
///
/// # Returns
///
/// A tuple of `(complete_blocks, remaining)`:
/// - `complete_blocks`: Data consisting of complete blocks ready for processing.
/// - `remaining`: Leftover partial block data to be buffered.
pub fn generic_block_update(
    input: &[u8],
    block_size: usize,
    pending: &[u8],
) -> (Vec<u8>, Vec<u8>) {
    let mut combined = Vec::with_capacity(pending.len() + input.len());
    combined.extend_from_slice(pending);
    combined.extend_from_slice(input);

    let full_blocks_len = (combined.len() / block_size) * block_size;
    let remaining = combined[full_blocks_len..].to_vec();
    combined.truncate(full_blocks_len);
    (combined, remaining)
}

/// Processes a stream-mode cipher update (no block alignment required).
///
/// Stream ciphers process data byte-by-byte, so all input is immediately
/// available for processing without buffering.
///
/// Translates the stream-update logic from `ossl_cipher_generic_stream_update()`
/// in `providers/implementations/ciphers/ciphercommon.c`.
///
/// # Parameters
///
/// - `input`: Input data to process.
///
/// # Returns
///
/// A copy of the input data ready for processing.
pub fn generic_stream_update(input: &[u8]) -> Vec<u8> {
    input.to_vec()
}

/// Validates a GCM authentication tag length.
///
/// GCM tags must be between 4 and 16 bytes (inclusive) and must be even.
/// The standard tag length is 16 bytes (128 bits).
///
/// Translates the tag length validation from `ossl_gcm_setiv()` in
/// `providers/implementations/ciphers/ciphercommon_gcm.c`.
///
/// # Parameters
///
/// - `tag_len`: The requested tag length in bytes.
///
/// # Returns
///
/// - `Ok(())` if the tag length is valid.
/// - `Err(String)` describing why the tag length is invalid.
pub fn gcm_validate_tag_len(tag_len: usize) -> Result<(), String> {
    if !(4..=16).contains(&tag_len) {
        return Err(format!("GCM tag length must be 4..=16 bytes, got {tag_len}"));
    }
    if tag_len % 2 != 0 {
        return Err(format!("GCM tag length must be even, got {tag_len}"));
    }
    Ok(())
}

/// Validates a CCM authentication tag length.
///
/// CCM tags must be between 4 and 16 bytes (inclusive) and must be even.
///
/// Translates the tag length validation from CCM operations in
/// `providers/implementations/ciphers/ciphercommon_ccm.c`.
///
/// # Parameters
///
/// - `tag_len`: The requested tag length in bytes.
///
/// # Returns
///
/// - `Ok(())` if the tag length is valid.
/// - `Err(String)` describing why the tag length is invalid.
pub fn ccm_validate_tag_len(tag_len: usize) -> Result<(), String> {
    if !(4..=16).contains(&tag_len) {
        return Err(format!("CCM tag length must be 4..=16 bytes, got {tag_len}"));
    }
    if tag_len % 2 != 0 {
        return Err(format!("CCM tag length must be even, got {tag_len}"));
    }
    Ok(())
}

/// Generates a random IV of the specified length.
///
/// Uses `rand::RngCore::fill_bytes()` from the OS CSPRNG to produce
/// cryptographically secure random IV bytes.
///
/// Translates the IV generation logic from `ossl_cipher_generic_initiv()`
/// in `providers/implementations/ciphers/ciphercommon.c`.
///
/// # Parameters
///
/// - `iv_len`: The desired IV length in bytes.
///
/// # Returns
///
/// A `Vec<u8>` containing `iv_len` random bytes.
pub fn generate_random_iv(iv_len: usize) -> Vec<u8> {
    use rand::RngCore;
    let mut iv = vec![0u8; iv_len];
    rand::thread_rng().fill_bytes(&mut iv);
    iv
}

/// Verifies an AEAD authentication tag against an expected value.
///
/// Performs a constant-time comparison to prevent timing side-channel
/// attacks. Both tags must have the same length.
///
/// Translates the tag verification from AEAD finalization routines in
/// `providers/implementations/ciphers/ciphercommon_gcm.c` and
/// `ciphercommon_ccm.c`.
///
/// # Parameters
///
/// - `computed`: The tag computed during decryption.
/// - `expected`: The expected tag provided by the caller.
///
/// # Returns
///
/// - `Ok(())` if the tags match.
/// - `Err(String)` if the tags don't match or have different lengths.
pub fn verify_tag(computed: &[u8], expected: &[u8]) -> Result<(), String> {
    use subtle::ConstantTimeEq;
    if computed.len() != expected.len() {
        return Err(format!(
            "tag length mismatch: computed {} bytes, expected {} bytes",
            computed.len(),
            expected.len()
        ));
    }
    if computed.ct_eq(expected).into() {
        Ok(())
    } else {
        Err("AEAD tag verification failed".to_string())
    }
}
