//! Shared type definitions for the OpenSSL Rust workspace.
//!
//! Provides newtype wrappers, algorithm identifiers ([`Nid`]), protocol version
//! constants ([`ProtocolVersion`]), padding modes ([`PaddingMode`]), key types
//! ([`KeyType`]), cipher modes ([`CipherMode`]), operation types
//! ([`OperationType`]), and the [`AlgorithmName`] trait — all foundational types
//! shared across every workspace crate.
//!
//! This module replaces the C forward declarations in `include/openssl/types.h`
//! (249 lines of opaque `typedef struct … *` forward declarations), the
//! compatibility aliases in `include/openssl/ossl_typ.h`, the core dispatch
//! types in `include/openssl/core.h`, and the integer `#define NID_*` constant
//! groups from `include/openssl/obj_mac.h`.
//!
//! # Design Principles
//!
//! - **Rule R5 (Nullability):** Every fallible conversion returns
//!   [`Option<T>`] instead of a sentinel value such as `0`, `-1`, or `""`.
//! - **Rule R6 (Lossless Casts):** The [`Nid`] newtype preserves the raw
//!   `i32` from C but all conversions use explicit methods (`as_raw`,
//!   `from_raw`), never bare `as` casts.
//! - **Rule R8 (Zero Unsafe):** This module contains zero `unsafe` blocks.
//! - **Rule R9 (Warning-Free):** Every public item carries a `///` doc comment
//!   and every enum variant is documented.
//!
//! # Feature Flag Convention
//!
//! Feature flags map to Cargo features, replacing C preprocessor
//! `OPENSSL_NO_*` guards:
//!
//! ```text
//! C:    #ifndef OPENSSL_NO_EC
//! Rust: #[cfg(feature = "ec")]
//! ```
//!
//! Standard features: `ec`, `rsa`, `dh`, `dsa`, `chacha`, `des`, `sm2`, `sm3`,
//! `sm4`, `cms`, `ocsp`, `ct`, `ts`, `cmp`, `hpke`, `quic`, `ech`, `fips`,
//! `legacy`.
//!
//! # Migration Reference
//!
//! | C Construct                        | Rust Equivalent                 |
//! |------------------------------------|---------------------------------|
//! | `NID_*` integer `#define` (obj_mac.h) | [`Nid`] newtype constants   |
//! | `SSL3_VERSION` / `TLS1_3_VERSION`  | [`ProtocolVersion`] enum        |
//! | `RSA_PKCS1_PADDING` etc.           | [`PaddingMode`] enum            |
//! | `EVP_PKEY_RSA` / `EVP_PKEY_EC`     | [`KeyType`] enum                |
//! | `EVP_CIPH_GCM_MODE` etc.           | [`CipherMode`] enum             |
//! | `OSSL_OP_DIGEST` etc.              | [`OperationType`] enum          |
//! | Forward `typedef struct … *`       | Concrete Rust structs elsewhere |

use serde::{Deserialize, Serialize};
use std::fmt;

// =============================================================================
// Nid — Numeric Identifier for ASN.1 Objects
// =============================================================================

/// Numeric identifier (NID) for ASN.1 objects and algorithm names.
///
/// In the C codebase, NIDs are plain `int` constants defined via `#define NID_*`
/// in `include/openssl/obj_mac.h` (generated by `crypto/objects/objects.pl`).
/// There are approximately 1 200 unique NIDs.  This newtype wrapper preserves
/// the raw `i32` value for FFI compatibility while providing a type-safe
/// interface for Rust code.
///
/// Only the most commonly referenced NIDs are declared here as associated
/// constants.  The full NID catalogue lives in the `openssl-crypto` crate
/// alongside OID-to-NID lookup tables.
///
/// # Examples
///
/// ```
/// use openssl_common::types::Nid;
///
/// let sha256 = Nid::SHA256;
/// assert_eq!(sha256.as_raw(), 672);
/// assert!(!sha256.is_undef());
///
/// let undef = Nid::UNDEF;
/// assert!(undef.is_undef());
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Nid(pub i32);

impl Nid {
    // ── Special sentinel ────────────────────────────────────────────────
    /// Undefined / unknown NID.  Corresponds to `NID_undef` (0).
    pub const UNDEF: Self = Self(0);

    // ── Digest algorithms ───────────────────────────────────────────────
    /// MD5 message digest (`NID_md5 = 4`).
    pub const MD5: Self = Self(4);
    /// SHA-1 message digest (`NID_sha1 = 64`).
    pub const SHA1: Self = Self(64);
    /// SHA-256 message digest (`NID_sha256 = 672`).
    pub const SHA256: Self = Self(672);
    /// SHA-384 message digest (`NID_sha384 = 673`).
    pub const SHA384: Self = Self(673);
    /// SHA-512 message digest (`NID_sha512 = 674`).
    pub const SHA512: Self = Self(674);
    /// SHA3-256 message digest (`NID_sha3_256 = 1097`).
    pub const SHA3_256: Self = Self(1097);
    /// SHA3-384 message digest (`NID_sha3_384 = 1098`).
    pub const SHA3_384: Self = Self(1098);
    /// SHA3-512 message digest (`NID_sha3_512 = 1099`).
    pub const SHA3_512: Self = Self(1099);

    // ── Cipher algorithms ───────────────────────────────────────────────
    /// AES-128-GCM authenticated encryption (`NID_aes_128_gcm = 895`).
    pub const AES_128_GCM: Self = Self(895);
    /// AES-256-GCM authenticated encryption (`NID_aes_256_gcm = 901`).
    pub const AES_256_GCM: Self = Self(901);
    /// ChaCha20-Poly1305 AEAD (`NID_chacha20_poly1305 = 1018`).
    pub const CHACHA20_POLY1305: Self = Self(1018);

    // ── Asymmetric key types ────────────────────────────────────────────
    /// RSA public-key algorithm (`NID_rsaEncryption = 6`).
    pub const RSA: Self = Self(6);
    /// Elliptic-curve public key (`NID_X9_62_id_ecPublicKey = 408`).
    pub const EC: Self = Self(408);
    /// Ed25519 signature algorithm (`NID_ED25519 = 1087`).
    pub const ED25519: Self = Self(1087);
    /// X25519 key-agreement algorithm (`NID_X25519 = 1034`).
    pub const X25519: Self = Self(1034);

    // ── Post-quantum algorithms ─────────────────────────────────────────
    /// ML-KEM-768 post-quantum KEM, FIPS 203 (`NID_ML_KEM_768 = 1455`).
    pub const ML_KEM_768: Self = Self(1455);

    // ── Accessors ───────────────────────────────────────────────────────

    /// Returns the raw `i32` value of this NID.
    ///
    /// Useful for serialization, FFI boundary crossings, and lookup tables.
    #[inline]
    pub const fn as_raw(self) -> i32 {
        self.0
    }

    /// Constructs a [`Nid`] from a raw `i32` value.
    ///
    /// No validation is performed — any `i32` is accepted.  Use the
    /// associated constants for well-known NIDs.
    #[inline]
    pub const fn from_raw(nid: i32) -> Self {
        Self(nid)
    }

    /// Returns `true` if this NID is the undefined sentinel ([`Nid::UNDEF`]).
    #[inline]
    pub const fn is_undef(self) -> bool {
        self.0 == Self::UNDEF.0
    }
}

impl fmt::Display for Nid {
    /// Formats the NID as `NID(<value>)` for human-readable output.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "NID({})", self.0)
    }
}

// =============================================================================
// ProtocolVersion — TLS/DTLS Protocol Version Identifiers
// =============================================================================

/// TLS and DTLS protocol version identifiers.
///
/// In C these are `#define` constants such as `SSL3_VERSION 0x0300` and
/// `TLS1_3_VERSION 0x0304` (see `include/openssl/prov_ssl.h`).  DTLS versions
/// use the bitwise-complement encoding defined in RFC 6347 § 4.1 where a
/// *higher* DTLS version has a *lower* numeric value.
///
/// # Rule R5 (Nullability)
///
/// [`ProtocolVersion::from_raw`] returns [`Option<ProtocolVersion>`] rather
/// than a sentinel value for unrecognised wire values.
///
/// # Examples
///
/// ```
/// use openssl_common::types::ProtocolVersion;
///
/// let tls13 = ProtocolVersion::Tls1_3;
/// assert_eq!(tls13.as_raw(), 0x0304);
/// assert!(tls13.is_tls());
/// assert!(!tls13.is_dtls());
///
/// assert!(ProtocolVersion::from_raw(0xFFFF).is_none());
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[repr(u16)]
pub enum ProtocolVersion {
    /// SSL 3.0 (`SSL3_VERSION = 0x0300`).  Deprecated — retained for
    /// downgrade detection and legacy interop testing.
    Ssl3_0 = 0x0300,
    /// TLS 1.0 (`TLS1_VERSION = 0x0301`).
    Tls1_0 = 0x0301,
    /// TLS 1.1 (`TLS1_1_VERSION = 0x0302`).
    Tls1_1 = 0x0302,
    /// TLS 1.2 (`TLS1_2_VERSION = 0x0303`).
    Tls1_2 = 0x0303,
    /// TLS 1.3 (`TLS1_3_VERSION = 0x0304`).
    Tls1_3 = 0x0304,
    /// DTLS 1.0 (`DTLS1_VERSION = 0xFEFF`).
    Dtls1_0 = 0xFEFF,
    /// DTLS 1.2 (`DTLS1_2_VERSION = 0xFEFD`).
    Dtls1_2 = 0xFEFD,
}

impl ProtocolVersion {
    /// Returns the on-the-wire `u16` value of this protocol version.
    #[inline]
    pub const fn as_raw(self) -> u16 {
        self as u16
    }

    /// Attempts to convert a raw `u16` wire value into a known
    /// [`ProtocolVersion`].
    ///
    /// Returns [`None`] for unrecognised values (Rule R5).
    #[inline]
    pub const fn from_raw(value: u16) -> Option<Self> {
        match value {
            0x0300 => Some(Self::Ssl3_0),
            0x0301 => Some(Self::Tls1_0),
            0x0302 => Some(Self::Tls1_1),
            0x0303 => Some(Self::Tls1_2),
            0x0304 => Some(Self::Tls1_3),
            0xFEFF => Some(Self::Dtls1_0),
            0xFEFD => Some(Self::Dtls1_2),
            _ => None,
        }
    }

    /// Returns `true` if this version belongs to the DTLS protocol family.
    ///
    /// DTLS versions are identified by having the high byte set to `0xFE`
    /// (RFC 6347 § 4.1).
    #[inline]
    pub const fn is_dtls(self) -> bool {
        (self.as_raw() >> 8) == 0xFE
    }

    /// Returns `true` if this version belongs to the TLS (or SSL) protocol
    /// family.
    ///
    /// All TLS/SSL versions have a high byte of `0x03`.
    #[inline]
    pub const fn is_tls(self) -> bool {
        (self.as_raw() >> 8) == 0x03
    }
}

impl fmt::Display for ProtocolVersion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Ssl3_0 => "SSLv3",
            Self::Tls1_0 => "TLSv1.0",
            Self::Tls1_1 => "TLSv1.1",
            Self::Tls1_2 => "TLSv1.2",
            Self::Tls1_3 => "TLSv1.3",
            Self::Dtls1_0 => "DTLSv1.0",
            Self::Dtls1_2 => "DTLSv1.2",
        };
        f.write_str(label)
    }
}

// =============================================================================
// PaddingMode — Cryptographic Padding Schemes
// =============================================================================

/// Cryptographic padding modes for symmetric and asymmetric operations.
///
/// Replaces C integer constants such as `RSA_PKCS1_PADDING`,
/// `RSA_PKCS1_OAEP_PADDING`, `RSA_PKCS1_PSS_PADDING`, and the
/// `EVP_PADDING_*` family.
///
/// # Examples
///
/// ```
/// use openssl_common::types::PaddingMode;
///
/// let mode = PaddingMode::Pkcs7;
/// assert_ne!(mode, PaddingMode::None);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PaddingMode {
    /// No padding.  The caller is responsible for ensuring the plaintext
    /// length is an exact multiple of the block size.
    None,
    /// PKCS#7 padding (RFC 5652 § 6.3).  Default for CBC-mode block ciphers.
    Pkcs7,
    /// OAEP with SHA-1 (`RSA_PKCS1_OAEP_PADDING` with default MGF).
    OaepSha1,
    /// OAEP with SHA-256 hash and MGF1-SHA-256.
    OaepSha256,
    /// RSA-PSS probabilistic signature padding (RFC 8017 § 8.1).
    Pss,
    /// ISO 10126 padding — random fill with length byte at the end.
    Iso10126,
    /// ANSI X9.23 padding — zero fill with length byte at the end.
    Ansi923,
}

impl fmt::Display for PaddingMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::None => "none",
            Self::Pkcs7 => "PKCS#7",
            Self::OaepSha1 => "OAEP-SHA1",
            Self::OaepSha256 => "OAEP-SHA256",
            Self::Pss => "PSS",
            Self::Iso10126 => "ISO-10126",
            Self::Ansi923 => "ANSI-X9.23",
        };
        f.write_str(label)
    }
}

// =============================================================================
// KeyType — Cryptographic Key Algorithm Families
// =============================================================================

/// Identifies the algorithm family of a cryptographic key.
///
/// Replaces the C `EVP_PKEY_RSA`, `EVP_PKEY_EC`, etc. integer constants
/// and provides methods for NID mapping and classification into asymmetric
/// vs. symmetric and classical vs. post-quantum categories.
///
/// # Examples
///
/// ```
/// use openssl_common::types::{KeyType, Nid};
///
/// let kt = KeyType::Ed25519;
/// assert!(kt.is_asymmetric());
/// assert!(!kt.is_post_quantum());
/// assert_eq!(kt.to_nid(), Nid::ED25519);
///
/// let pq = KeyType::MlKem768;
/// assert!(pq.is_post_quantum());
/// assert!(pq.is_asymmetric());
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum KeyType {
    /// RSA key (`NID_rsaEncryption = 6`).
    Rsa,
    /// RSA-PSS key (`NID_rsassaPss = 912`).
    RsaPss,
    /// Diffie-Hellman key (`NID_dhKeyAgreement = 28`).
    Dh,
    /// DSA key (`NID_dsa = 116`).
    Dsa,
    /// Elliptic-curve key — generic NIST / Brainpool curves
    /// (`NID_X9_62_id_ecPublicKey = 408`).
    Ec,
    /// Ed25519 signing key (`NID_ED25519 = 1087`).
    Ed25519,
    /// Ed448 signing key (`NID_ED448 = 1088`).
    Ed448,
    /// X25519 key-agreement key (`NID_X25519 = 1034`).
    X25519,
    /// X448 key-agreement key (`NID_X448 = 1035`).
    X448,
    /// ML-KEM-512 post-quantum KEM, FIPS 203 (`NID_ML_KEM_512 = 1454`).
    MlKem512,
    /// ML-KEM-768 post-quantum KEM, FIPS 203 (`NID_ML_KEM_768 = 1455`).
    MlKem768,
    /// ML-KEM-1024 post-quantum KEM, FIPS 203 (`NID_ML_KEM_1024 = 1456`).
    MlKem1024,
    /// ML-DSA-44 post-quantum signature, FIPS 204 (`NID_ML_DSA_44 = 1457`).
    MlDsa44,
    /// ML-DSA-65 post-quantum signature, FIPS 204 (`NID_ML_DSA_65 = 1458`).
    MlDsa65,
    /// ML-DSA-87 post-quantum signature, FIPS 204 (`NID_ML_DSA_87 = 1459`).
    MlDsa87,
    /// SLH-DSA (Stateless Hash-Based Digital Signature Algorithm), FIPS 205.
    /// Represented generically — specific parameter sets distinguished at
    /// a higher level.  Uses `NID_SLH_DSA_SHA2_128s = 1460` as the canonical NID.
    SlhDsa,
    /// LMS (Leighton-Micali Signature), SP 800-208.
    /// Uses `NID_id_alg_hss_lms_hashsig = 1501` as the canonical NID.
    Lms,
    /// HMAC symmetric key (`NID_hmac = 855`).
    Hmac,
    /// CMAC symmetric key (`NID_cmac = 894`).
    Cmac,
}

/// NID constant for RSA-PSS (`NID_rsassaPss`).
const NID_RSA_PSS: Nid = Nid(912);
/// NID constant for Diffie-Hellman (`NID_dhKeyAgreement`).
const NID_DH: Nid = Nid(28);
/// NID constant for DSA (`NID_dsa`).
const NID_DSA: Nid = Nid(116);
/// NID constant for Ed448 (`NID_ED448`).
const NID_ED448: Nid = Nid(1088);
/// NID constant for X448 (`NID_X448`).
const NID_X448: Nid = Nid(1035);
/// NID constant for ML-KEM-512 (`NID_ML_KEM_512`).
const NID_ML_KEM_512: Nid = Nid(1454);
/// NID constant for ML-KEM-1024 (`NID_ML_KEM_1024`).
const NID_ML_KEM_1024: Nid = Nid(1456);
/// NID constant for ML-DSA-44 (`NID_ML_DSA_44`).
const NID_ML_DSA_44: Nid = Nid(1457);
/// NID constant for ML-DSA-65 (`NID_ML_DSA_65`).
const NID_ML_DSA_65: Nid = Nid(1458);
/// NID constant for ML-DSA-87 (`NID_ML_DSA_87`).
const NID_ML_DSA_87: Nid = Nid(1459);
/// NID constant for SLH-DSA (`NID_SLH_DSA_SHA2_128s` — canonical representative).
const NID_SLH_DSA: Nid = Nid(1460);
/// NID constant for LMS/HSS (`NID_id_alg_hss_lms_hashsig`).
const NID_LMS: Nid = Nid(1501);
/// NID constant for HMAC (`NID_hmac`).
const NID_HMAC: Nid = Nid(855);
/// NID constant for CMAC (`NID_cmac`).
const NID_CMAC: Nid = Nid(894);

impl KeyType {
    /// Maps this key type to its canonical [`Nid`].
    ///
    /// The mapping matches the C `EVP_PKEY_*` → `NID_*` correspondence
    /// defined across `include/openssl/evp.h` and `include/openssl/obj_mac.h`.
    #[inline]
    pub const fn to_nid(self) -> Nid {
        match self {
            Self::Rsa => Nid::RSA,
            Self::RsaPss => NID_RSA_PSS,
            Self::Dh => NID_DH,
            Self::Dsa => NID_DSA,
            Self::Ec => Nid::EC,
            Self::Ed25519 => Nid::ED25519,
            Self::Ed448 => NID_ED448,
            Self::X25519 => Nid::X25519,
            Self::X448 => NID_X448,
            Self::MlKem512 => NID_ML_KEM_512,
            Self::MlKem768 => Nid::ML_KEM_768,
            Self::MlKem1024 => NID_ML_KEM_1024,
            Self::MlDsa44 => NID_ML_DSA_44,
            Self::MlDsa65 => NID_ML_DSA_65,
            Self::MlDsa87 => NID_ML_DSA_87,
            Self::SlhDsa => NID_SLH_DSA,
            Self::Lms => NID_LMS,
            Self::Hmac => NID_HMAC,
            Self::Cmac => NID_CMAC,
        }
    }

    /// Attempts to determine the [`KeyType`] from a [`Nid`].
    ///
    /// Returns [`None`] if the NID does not correspond to any known key type
    /// (Rule R5 — no sentinel values).
    #[inline]
    pub const fn from_nid(nid: Nid) -> Option<Self> {
        match nid.0 {
            6 => Some(Self::Rsa),          // NID_rsaEncryption
            912 => Some(Self::RsaPss),     // NID_rsassaPss
            28 => Some(Self::Dh),          // NID_dhKeyAgreement
            116 => Some(Self::Dsa),        // NID_dsa
            408 => Some(Self::Ec),         // NID_X9_62_id_ecPublicKey
            1087 => Some(Self::Ed25519),   // NID_ED25519
            1088 => Some(Self::Ed448),     // NID_ED448
            1034 => Some(Self::X25519),    // NID_X25519
            1035 => Some(Self::X448),      // NID_X448
            1454 => Some(Self::MlKem512),  // NID_ML_KEM_512
            1455 => Some(Self::MlKem768),  // NID_ML_KEM_768
            1456 => Some(Self::MlKem1024), // NID_ML_KEM_1024
            1457 => Some(Self::MlDsa44),   // NID_ML_DSA_44
            1458 => Some(Self::MlDsa65),   // NID_ML_DSA_65
            1459 => Some(Self::MlDsa87),   // NID_ML_DSA_87
            1460 => Some(Self::SlhDsa),    // NID_SLH_DSA_SHA2_128s
            1501 => Some(Self::Lms),       // NID_id_alg_hss_lms_hashsig
            855 => Some(Self::Hmac),       // NID_hmac
            894 => Some(Self::Cmac),       // NID_cmac
            _ => None,
        }
    }

    /// Returns `true` if this key type belongs to an asymmetric (public-key)
    /// algorithm.
    ///
    /// Symmetric-only key types ([`KeyType::Hmac`], [`KeyType::Cmac`]) return
    /// `false`.
    #[inline]
    pub const fn is_asymmetric(self) -> bool {
        match self {
            Self::Hmac | Self::Cmac => false,
            Self::Rsa
            | Self::RsaPss
            | Self::Dh
            | Self::Dsa
            | Self::Ec
            | Self::Ed25519
            | Self::Ed448
            | Self::X25519
            | Self::X448
            | Self::MlKem512
            | Self::MlKem768
            | Self::MlKem1024
            | Self::MlDsa44
            | Self::MlDsa65
            | Self::MlDsa87
            | Self::SlhDsa
            | Self::Lms => true,
        }
    }

    /// Returns `true` if this key type is a post-quantum algorithm.
    ///
    /// Post-quantum key types are ML-KEM (FIPS 203), ML-DSA (FIPS 204),
    /// SLH-DSA (FIPS 205), and LMS (SP 800-208).
    #[inline]
    pub const fn is_post_quantum(self) -> bool {
        match self {
            Self::MlKem512
            | Self::MlKem768
            | Self::MlKem1024
            | Self::MlDsa44
            | Self::MlDsa65
            | Self::MlDsa87
            | Self::SlhDsa
            | Self::Lms => true,
            Self::Rsa
            | Self::RsaPss
            | Self::Dh
            | Self::Dsa
            | Self::Ec
            | Self::Ed25519
            | Self::Ed448
            | Self::X25519
            | Self::X448
            | Self::Hmac
            | Self::Cmac => false,
        }
    }
}

impl fmt::Display for KeyType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Rsa => "RSA",
            Self::RsaPss => "RSA-PSS",
            Self::Dh => "DH",
            Self::Dsa => "DSA",
            Self::Ec => "EC",
            Self::Ed25519 => "Ed25519",
            Self::Ed448 => "Ed448",
            Self::X25519 => "X25519",
            Self::X448 => "X448",
            Self::MlKem512 => "ML-KEM-512",
            Self::MlKem768 => "ML-KEM-768",
            Self::MlKem1024 => "ML-KEM-1024",
            Self::MlDsa44 => "ML-DSA-44",
            Self::MlDsa65 => "ML-DSA-65",
            Self::MlDsa87 => "ML-DSA-87",
            Self::SlhDsa => "SLH-DSA",
            Self::Lms => "LMS",
            Self::Hmac => "HMAC",
            Self::Cmac => "CMAC",
        };
        f.write_str(label)
    }
}

// =============================================================================
// CipherMode — Block Cipher Modes of Operation
// =============================================================================

/// Block cipher modes of operation.
///
/// Replaces the C `EVP_CIPH_ECB_MODE`, `EVP_CIPH_CBC_MODE`, … constants
/// defined in `include/openssl/evp.h` and the `EVP_CIPH_*_MODE` flag family.
///
/// # Examples
///
/// ```
/// use openssl_common::types::CipherMode;
///
/// let gcm = CipherMode::Gcm;
/// assert_ne!(gcm, CipherMode::Ecb);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CipherMode {
    /// Electronic Codebook (ECB) mode.
    Ecb,
    /// Cipher Block Chaining (CBC) mode.
    Cbc,
    /// Cipher Feedback (CFB) mode.
    Cfb,
    /// Output Feedback (OFB) mode.
    Ofb,
    /// Counter (CTR) mode.
    Ctr,
    /// Galois/Counter Mode (GCM) — authenticated encryption.
    Gcm,
    /// Counter with CBC-MAC (CCM) — authenticated encryption.
    Ccm,
    /// XEX-based Tweaked-codebook mode with ciphertext Stealing (XTS).
    Xts,
    /// AES Key Wrap (RFC 3394).
    Wrap,
    /// AES Key Wrap with Padding (RFC 5649).
    WrapPad,
    /// Offset Codebook Mode (OCB) — authenticated encryption.
    Ocb,
    /// Synthetic Initialization Vector (SIV) mode (RFC 5297).
    Siv,
    /// AES-GCM-SIV (RFC 8452) — nonce-misuse-resistant AEAD.
    GcmSiv,
    /// Stream cipher mode, e.g. `ChaCha20` or `RC4`.
    Stream,
}

impl fmt::Display for CipherMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Ecb => "ECB",
            Self::Cbc => "CBC",
            Self::Cfb => "CFB",
            Self::Ofb => "OFB",
            Self::Ctr => "CTR",
            Self::Gcm => "GCM",
            Self::Ccm => "CCM",
            Self::Xts => "XTS",
            Self::Wrap => "WRAP",
            Self::WrapPad => "WRAP-PAD",
            Self::Ocb => "OCB",
            Self::Siv => "SIV",
            Self::GcmSiv => "GCM-SIV",
            Self::Stream => "STREAM",
        };
        f.write_str(label)
    }
}

// =============================================================================
// OperationType — Provider Operation Categories
// =============================================================================

/// Categories of cryptographic operations dispatched through the provider
/// framework.
///
/// Replaces the C `OSSL_OP_DIGEST`, `OSSL_OP_CIPHER`, … integer constants
/// defined in `include/openssl/core_dispatch.h`.  Each variant corresponds
/// to a set of dispatch function IDs that a provider must implement to
/// supply the operation.
///
/// # Examples
///
/// ```
/// use openssl_common::types::OperationType;
///
/// let op = OperationType::Digest;
/// assert_ne!(op, OperationType::Cipher);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OperationType {
    /// Message digest / hash operations (`OSSL_OP_DIGEST`).
    Digest,
    /// Symmetric cipher operations (`OSSL_OP_CIPHER`).
    Cipher,
    /// Message Authentication Code operations (`OSSL_OP_MAC`).
    Mac,
    /// Key Derivation Function operations (`OSSL_OP_KDF`).
    Kdf,
    /// Random number generation operations (`OSSL_OP_RAND`).
    Rand,
    /// Key management operations (`OSSL_OP_KEYMGMT`).
    KeyMgmt,
    /// Digital signature operations (`OSSL_OP_SIGNATURE`).
    Signature,
    /// Asymmetric cipher operations (`OSSL_OP_ASYM_CIPHER`).
    AsymCipher,
    /// Key Encapsulation Mechanism operations (`OSSL_OP_KEM`).
    Kem,
    /// Key exchange / agreement operations (`OSSL_OP_KEYEXCH`).
    KeyExch,
    /// Encoder/decoder (serialization) operations (`OSSL_OP_ENCODER` /
    /// `OSSL_OP_DECODER`).
    EncoderDecoder,
    /// Object store operations (`OSSL_OP_STORE`).
    Store,
    /// Symmetric (opaque/secret) key management operations (`OSSL_OP_SKEYMGMT`).
    ///
    /// Distinct from [`KeyMgmt`](Self::KeyMgmt) which handles asymmetric key
    /// management.  In C OpenSSL, `OSSL_OP_STORE` and `OSSL_OP_SKEYMGMT` are
    /// separate operation types dispatched independently by the provider
    /// framework.
    SKeyMgmt,
}

impl fmt::Display for OperationType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Digest => "digest",
            Self::Cipher => "cipher",
            Self::Mac => "mac",
            Self::Kdf => "kdf",
            Self::Rand => "rand",
            Self::KeyMgmt => "keymgmt",
            Self::Signature => "signature",
            Self::AsymCipher => "asymcipher",
            Self::Kem => "kem",
            Self::KeyExch => "keyexch",
            Self::EncoderDecoder => "encoder_decoder",
            Self::Store => "store",
            Self::SKeyMgmt => "skeymgmt",
        };
        f.write_str(label)
    }
}

// =============================================================================
// AlgorithmName — Trait for Named Algorithms
// =============================================================================

/// Trait for types that represent a named cryptographic algorithm.
///
/// Implementors provide a human-readable algorithm name and its
/// corresponding [`Nid`].  This is used by the provider framework
/// to register and look up algorithm implementations by name.
///
/// # Examples
///
/// ```
/// use openssl_common::types::{AlgorithmName, Nid};
///
/// struct Sha256Digest;
///
/// impl AlgorithmName for Sha256Digest {
///     fn algorithm_name(&self) -> &'static str { "SHA2-256" }
///     fn nid(&self) -> Nid { Nid::SHA256 }
/// }
///
/// let d = Sha256Digest;
/// assert_eq!(d.algorithm_name(), "SHA2-256");
/// assert_eq!(d.nid(), Nid::SHA256);
/// ```
pub trait AlgorithmName {
    /// Returns the canonical algorithm name string.
    ///
    /// The returned name should match the string used in provider
    /// `OSSL_ALGORITHM` registration tables (e.g. `"SHA2-256"`, `"AES-128-GCM"`).
    fn algorithm_name(&self) -> &'static str;

    /// Returns the numeric identifier ([`Nid`]) for this algorithm.
    fn nid(&self) -> Nid;
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    // ── Nid tests ───────────────────────────────────────────────────────

    #[test]
    fn nid_undef_is_zero() {
        assert_eq!(Nid::UNDEF.as_raw(), 0);
        assert!(Nid::UNDEF.is_undef());
    }

    #[test]
    fn nid_from_raw_roundtrip() {
        let nid = Nid::from_raw(672);
        assert_eq!(nid, Nid::SHA256);
        assert_eq!(nid.as_raw(), 672);
    }

    #[test]
    fn nid_display() {
        assert_eq!(format!("{}", Nid::SHA256), "NID(672)");
        assert_eq!(format!("{}", Nid::UNDEF), "NID(0)");
    }

    #[test]
    fn nid_ordering() {
        assert!(Nid::MD5 < Nid::SHA1);
        assert!(Nid::SHA1 < Nid::SHA256);
    }

    #[test]
    fn nid_constants_match_c_values() {
        assert_eq!(Nid::MD5.as_raw(), 4);
        assert_eq!(Nid::SHA1.as_raw(), 64);
        assert_eq!(Nid::SHA256.as_raw(), 672);
        assert_eq!(Nid::SHA384.as_raw(), 673);
        assert_eq!(Nid::SHA512.as_raw(), 674);
        assert_eq!(Nid::SHA3_256.as_raw(), 1097);
        assert_eq!(Nid::SHA3_384.as_raw(), 1098);
        assert_eq!(Nid::SHA3_512.as_raw(), 1099);
        assert_eq!(Nid::AES_128_GCM.as_raw(), 895);
        assert_eq!(Nid::AES_256_GCM.as_raw(), 901);
        assert_eq!(Nid::CHACHA20_POLY1305.as_raw(), 1018);
        assert_eq!(Nid::RSA.as_raw(), 6);
        assert_eq!(Nid::EC.as_raw(), 408);
        assert_eq!(Nid::ED25519.as_raw(), 1087);
        assert_eq!(Nid::X25519.as_raw(), 1034);
        assert_eq!(Nid::ML_KEM_768.as_raw(), 1455);
    }

    #[test]
    fn nid_non_undef() {
        assert!(!Nid::SHA256.is_undef());
        assert!(!Nid::RSA.is_undef());
    }

    // ── ProtocolVersion tests ───────────────────────────────────────────

    #[test]
    fn protocol_version_raw_roundtrip() {
        for &(ver, raw) in &[
            (ProtocolVersion::Ssl3_0, 0x0300u16),
            (ProtocolVersion::Tls1_0, 0x0301),
            (ProtocolVersion::Tls1_1, 0x0302),
            (ProtocolVersion::Tls1_2, 0x0303),
            (ProtocolVersion::Tls1_3, 0x0304),
            (ProtocolVersion::Dtls1_0, 0xFEFF),
            (ProtocolVersion::Dtls1_2, 0xFEFD),
        ] {
            assert_eq!(ver.as_raw(), raw);
            assert_eq!(ProtocolVersion::from_raw(raw), Some(ver));
        }
    }

    #[test]
    fn protocol_version_unknown_returns_none() {
        assert_eq!(ProtocolVersion::from_raw(0x0000), None);
        assert_eq!(ProtocolVersion::from_raw(0xFFFF), None);
        assert_eq!(ProtocolVersion::from_raw(0x0305), None);
    }

    #[test]
    fn protocol_version_is_tls() {
        assert!(ProtocolVersion::Ssl3_0.is_tls());
        assert!(ProtocolVersion::Tls1_0.is_tls());
        assert!(ProtocolVersion::Tls1_3.is_tls());
        assert!(!ProtocolVersion::Dtls1_0.is_tls());
        assert!(!ProtocolVersion::Dtls1_2.is_tls());
    }

    #[test]
    fn protocol_version_is_dtls() {
        assert!(ProtocolVersion::Dtls1_0.is_dtls());
        assert!(ProtocolVersion::Dtls1_2.is_dtls());
        assert!(!ProtocolVersion::Tls1_3.is_dtls());
        assert!(!ProtocolVersion::Ssl3_0.is_dtls());
    }

    #[test]
    fn protocol_version_display() {
        assert_eq!(format!("{}", ProtocolVersion::Tls1_3), "TLSv1.3");
        assert_eq!(format!("{}", ProtocolVersion::Dtls1_2), "DTLSv1.2");
    }

    // ── PaddingMode tests ───────────────────────────────────────────────

    #[test]
    fn padding_mode_equality() {
        assert_eq!(PaddingMode::Pkcs7, PaddingMode::Pkcs7);
        assert_ne!(PaddingMode::None, PaddingMode::Pkcs7);
    }

    #[test]
    fn padding_mode_display() {
        assert_eq!(format!("{}", PaddingMode::None), "none");
        assert_eq!(format!("{}", PaddingMode::Pkcs7), "PKCS#7");
        assert_eq!(format!("{}", PaddingMode::OaepSha256), "OAEP-SHA256");
        assert_eq!(format!("{}", PaddingMode::Pss), "PSS");
    }

    // ── KeyType tests ───────────────────────────────────────────────────

    #[test]
    fn key_type_to_nid_roundtrip() {
        let key_types = [
            KeyType::Rsa,
            KeyType::RsaPss,
            KeyType::Dh,
            KeyType::Dsa,
            KeyType::Ec,
            KeyType::Ed25519,
            KeyType::Ed448,
            KeyType::X25519,
            KeyType::X448,
            KeyType::MlKem512,
            KeyType::MlKem768,
            KeyType::MlKem1024,
            KeyType::MlDsa44,
            KeyType::MlDsa65,
            KeyType::MlDsa87,
            KeyType::SlhDsa,
            KeyType::Lms,
            KeyType::Hmac,
            KeyType::Cmac,
        ];
        for kt in key_types {
            let nid = kt.to_nid();
            let recovered = KeyType::from_nid(nid);
            assert_eq!(recovered, Some(kt), "roundtrip failed for {kt:?}");
        }
    }

    #[test]
    fn key_type_from_nid_unknown_returns_none() {
        assert_eq!(KeyType::from_nid(Nid::UNDEF), None);
        assert_eq!(KeyType::from_nid(Nid::from_raw(99999)), None);
    }

    #[test]
    fn key_type_asymmetric() {
        assert!(KeyType::Rsa.is_asymmetric());
        assert!(KeyType::Ec.is_asymmetric());
        assert!(KeyType::Ed25519.is_asymmetric());
        assert!(KeyType::MlKem768.is_asymmetric());
        assert!(!KeyType::Hmac.is_asymmetric());
        assert!(!KeyType::Cmac.is_asymmetric());
    }

    #[test]
    fn key_type_post_quantum() {
        assert!(KeyType::MlKem512.is_post_quantum());
        assert!(KeyType::MlKem768.is_post_quantum());
        assert!(KeyType::MlKem1024.is_post_quantum());
        assert!(KeyType::MlDsa44.is_post_quantum());
        assert!(KeyType::MlDsa65.is_post_quantum());
        assert!(KeyType::MlDsa87.is_post_quantum());
        assert!(KeyType::SlhDsa.is_post_quantum());
        assert!(KeyType::Lms.is_post_quantum());
        assert!(!KeyType::Rsa.is_post_quantum());
        assert!(!KeyType::Ec.is_post_quantum());
        assert!(!KeyType::Hmac.is_post_quantum());
    }

    #[test]
    fn key_type_display() {
        assert_eq!(format!("{}", KeyType::Rsa), "RSA");
        assert_eq!(format!("{}", KeyType::MlKem768), "ML-KEM-768");
        assert_eq!(format!("{}", KeyType::Ed25519), "Ed25519");
    }

    // ── CipherMode tests ────────────────────────────────────────────────

    #[test]
    fn cipher_mode_equality() {
        assert_eq!(CipherMode::Gcm, CipherMode::Gcm);
        assert_ne!(CipherMode::Gcm, CipherMode::Cbc);
    }

    #[test]
    fn cipher_mode_display() {
        assert_eq!(format!("{}", CipherMode::Gcm), "GCM");
        assert_eq!(format!("{}", CipherMode::Cbc), "CBC");
        assert_eq!(format!("{}", CipherMode::Stream), "STREAM");
        assert_eq!(format!("{}", CipherMode::GcmSiv), "GCM-SIV");
    }

    // ── OperationType tests ─────────────────────────────────────────────

    #[test]
    fn operation_type_equality() {
        assert_eq!(OperationType::Digest, OperationType::Digest);
        assert_ne!(OperationType::Digest, OperationType::Cipher);
    }

    #[test]
    fn operation_type_display() {
        assert_eq!(format!("{}", OperationType::Digest), "digest");
        assert_eq!(format!("{}", OperationType::Cipher), "cipher");
        assert_eq!(
            format!("{}", OperationType::EncoderDecoder),
            "encoder_decoder"
        );
        assert_eq!(format!("{}", OperationType::Store), "store");
        assert_eq!(format!("{}", OperationType::SKeyMgmt), "skeymgmt");
    }

    // ── AlgorithmName trait tests ───────────────────────────────────────

    #[test]
    fn algorithm_name_trait() {
        struct TestAlgo;
        impl AlgorithmName for TestAlgo {
            fn algorithm_name(&self) -> &'static str {
                "TEST-ALGO"
            }
            fn nid(&self) -> Nid {
                Nid::SHA256
            }
        }

        let algo = TestAlgo;
        assert_eq!(algo.algorithm_name(), "TEST-ALGO");
        assert_eq!(algo.nid(), Nid::SHA256);
    }

    // ── Serde serialization tests ───────────────────────────────────────

    #[test]
    fn nid_serde_roundtrip() {
        let nid = Nid::SHA256;
        let json = serde_json::to_string(&nid).expect("serialize nid");
        let recovered: Nid = serde_json::from_str(&json).expect("deserialize nid");
        assert_eq!(nid, recovered);
    }

    #[test]
    fn protocol_version_serde_roundtrip() {
        let ver = ProtocolVersion::Tls1_3;
        let json = serde_json::to_string(&ver).expect("serialize version");
        let recovered: ProtocolVersion = serde_json::from_str(&json).expect("deserialize version");
        assert_eq!(ver, recovered);
    }

    #[test]
    fn key_type_serde_roundtrip() {
        let kt = KeyType::MlKem768;
        let json = serde_json::to_string(&kt).expect("serialize key type");
        let recovered: KeyType = serde_json::from_str(&json).expect("deserialize key type");
        assert_eq!(kt, recovered);
    }

    #[test]
    fn cipher_mode_serde_roundtrip() {
        let cm = CipherMode::Gcm;
        let json = serde_json::to_string(&cm).expect("serialize cipher mode");
        let recovered: CipherMode = serde_json::from_str(&json).expect("deserialize cipher mode");
        assert_eq!(cm, recovered);
    }

    #[test]
    fn padding_mode_serde_roundtrip() {
        let pm = PaddingMode::OaepSha256;
        let json = serde_json::to_string(&pm).expect("serialize padding mode");
        let recovered: PaddingMode = serde_json::from_str(&json).expect("deserialize padding mode");
        assert_eq!(pm, recovered);
    }

    #[test]
    fn operation_type_serde_roundtrip() {
        let ot = OperationType::Kem;
        let json = serde_json::to_string(&ot).expect("serialize op type");
        let recovered: OperationType = serde_json::from_str(&json).expect("deserialize op type");
        assert_eq!(ot, recovered);
    }
}
